name: Node.js CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      type:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Type of Run'
        # Default value if no value is explicitly provided
        default: 'none'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      env:
         NODE_VER: ${{secrets.NODE_VERSION}}
      with:
        node-version: ${{env.NODE_VER}}

    - name: Install dependencies
      run: | 
         npm install
         echo "$GITHUB_WORKFLOW $GITHUB_REF"
         echo run is a ${{ github.event.inputs.type }}
    - name: Run tests
      id: test_result
      run: |
         results="${npm test | grep Tests}"
         echo "::set-output name=TEST_RESULT::$results"
         echo "steps.test_result.outputs.TEST_RESULT"
     
