name: Monitor Workflow Runs

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - requested
      - completed

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps here as needed for monitoring
      # For example, send notifications, log details, etc.
