name: Test

on:
  push:
  workflow_run:
    workflows: [NodeCI]
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bhanuraina/test_nodejs/actions/runs
